export type AccessMode =
  | "official_bulk_csv"
  | "open_data"
  | "gated_request"
  | "official_portal"
  | "missing_money";

export interface StateDirectoryEntry {
  state: string;
  name: string;
  agency: string;
  officialUrl: string;
  accessMode: AccessMode;
  missingMoneyUrl: string;
  machineReadable: boolean;
  notes: string;
}

const missingMoneyUrl = (state: string) => `https://missingmoney.com/app/claim-search?state=${state}`;

export const STATE_DIRECTORY: Record<string, StateDirectoryEntry> = {
  AL: { state: "AL", name: "Alabama", agency: "Alabama State Treasury", officialUrl: "https://alabama.findyourunclaimedproperty.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("AL"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  AK: { state: "AK", name: "Alaska", agency: "Alaska Department of Revenue, Treasury Division", officialUrl: "https://treasury.dor.alaska.gov/Unclaimed-Property", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("AK"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  AZ: { state: "AZ", name: "Arizona", agency: "Arizona Department of Revenue", officialUrl: "https://azdor.gov/unclaimed-property", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("AZ"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  AR: { state: "AR", name: "Arkansas", agency: "Arkansas Auditor of State", officialUrl: "https://auditor.ar.gov/unclaimed-property", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("AR"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  CA: { state: "CA", name: "California", agency: "California State Controller's Office", officialUrl: "https://www.sco.ca.gov/upd_download_property_records.html", accessMode: "official_bulk_csv", missingMoneyUrl: missingMoneyUrl("CA"), machineReadable: true, notes: "Official bulk CSV files, including $500+ records. Best current high-value source." },
  CO: { state: "CO", name: "Colorado", agency: "Colorado State Treasurer", officialUrl: "https://colorado.findyourunclaimedproperty.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("CO"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  CT: { state: "CT", name: "Connecticut", agency: "Connecticut Office of the Treasurer", officialUrl: "https://ctbiglist.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("CT"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  DE: { state: "DE", name: "Delaware", agency: "Delaware Office of Unclaimed Property", officialUrl: "https://unclaimedproperty.delaware.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("DE"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  DC: { state: "DC", name: "District of Columbia", agency: "District of Columbia Office of Finance and Treasury", officialUrl: "https://dc.findyourunclaimedproperty.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("DC"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  FL: { state: "FL", name: "Florida", agency: "Florida Department of Financial Services", officialUrl: "https://www.fltreasurehunt.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("FL"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  GA: { state: "GA", name: "Georgia", agency: "Georgia Department of Revenue", officialUrl: "https://dor.georgia.gov/unclaimed-property-program", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("GA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  HI: { state: "HI", name: "Hawaii", agency: "Hawaii Department of Budget and Finance", officialUrl: "https://budget.hawaii.gov/finance/unclaimedproperty/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("HI"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  ID: { state: "ID", name: "Idaho", agency: "Idaho State Treasurer's Office", officialUrl: "https://yourmoney.idaho.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("ID"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  IL: { state: "IL", name: "Illinois", agency: "Illinois State Treasurer", officialUrl: "https://icash.illinoistreasurer.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("IL"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  IN: { state: "IN", name: "Indiana", agency: "Indiana Attorney General", officialUrl: "https://indianaunclaimed.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("IN"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  IA: { state: "IA", name: "Iowa", agency: "Iowa State Treasurer", officialUrl: "https://www.iowatreasurer.gov/for-citizens/great-iowa-treasure-hunt", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("IA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  KS: { state: "KS", name: "Kansas", agency: "Kansas State Treasurer", officialUrl: "https://kansascash.ks.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("KS"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  KY: { state: "KY", name: "Kentucky", agency: "Kentucky State Treasurer", officialUrl: "https://treasury.ky.gov/unclaimedproperty/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("KY"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  LA: { state: "LA", name: "Louisiana", agency: "Louisiana Department of Treasury", officialUrl: "https://LaCashClaim.org/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("LA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  ME: { state: "ME", name: "Maine", agency: "Maine State Treasurer", officialUrl: "https://maineunclaimedproperty.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("ME"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MD: { state: "MD", name: "Maryland", agency: "Maryland Comptroller", officialUrl: "https://www.marylandtaxes.gov/unclaimed-property/index.php", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MD"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MA: { state: "MA", name: "Massachusetts", agency: "Massachusetts State Treasurer", officialUrl: "https://www.findmassmoney.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MI: { state: "MI", name: "Michigan", agency: "Michigan Department of Treasury", officialUrl: "https://unclaimedproperty.michigan.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MI"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MN: { state: "MN", name: "Minnesota", agency: "Minnesota Department of Commerce", officialUrl: "https://mn.gov/commerce/money/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MN"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MS: { state: "MS", name: "Mississippi", agency: "Mississippi State Treasurer", officialUrl: "https://treasury.ms.gov/for-citizens/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MS"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MO: { state: "MO", name: "Missouri", agency: "Missouri State Treasurer", officialUrl: "https://treasurer.mo.gov/unclaimedproperty/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MO"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  MT: { state: "MT", name: "Montana", agency: "Montana Department of Revenue", officialUrl: "https://mtrevenue.gov/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("MT"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NE: { state: "NE", name: "Nebraska", agency: "Nebraska State Treasurer", officialUrl: "https://treasurer.nebraska.gov/up/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NE"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NV: { state: "NV", name: "Nevada", agency: "Nevada State Treasurer", officialUrl: "https://www.nvup.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NV"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NH: { state: "NH", name: "New Hampshire", agency: "New Hampshire Treasury Department", officialUrl: "https://newhampshire.findyourunclaimedproperty.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NH"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NJ: { state: "NJ", name: "New Jersey", agency: "New Jersey Unclaimed Property Administration", officialUrl: "https://www.unclaimedproperty.nj.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NJ"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NM: { state: "NM", name: "New Mexico", agency: "New Mexico Taxation and Revenue Department", officialUrl: "https://www.tax.newmexico.gov/individuals/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NM"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NY: { state: "NY", name: "New York", agency: "New York State Comptroller", officialUrl: "https://www.osc.ny.gov/unclaimed-funds", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NY"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  NC: { state: "NC", name: "North Carolina", agency: "North Carolina Department of State Treasurer", officialUrl: "https://www.nccash.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("NC"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  ND: { state: "ND", name: "North Dakota", agency: "North Dakota Department of Trust Lands", officialUrl: "https://unclaimedproperty.nd.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("ND"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  OH: { state: "OH", name: "Ohio", agency: "Ohio Department of Commerce", officialUrl: "https://com.ohio.gov/divisions-and-programs/unclaimed-funds", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("OH"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  OK: { state: "OK", name: "Oklahoma", agency: "Oklahoma State Treasurer", officialUrl: "https://www.oktreasure.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("OK"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  OR: { state: "OR", name: "Oregon", agency: "Oregon State Treasury", officialUrl: "https://unclaimed.oregon.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("OR"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  PA: { state: "PA", name: "Pennsylvania", agency: "Pennsylvania Treasury", officialUrl: "https://www.patreasury.gov/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("PA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  RI: { state: "RI", name: "Rhode Island", agency: "Rhode Island Office of the General Treasurer", officialUrl: "https://findrimoney.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("RI"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  SC: { state: "SC", name: "South Carolina", agency: "South Carolina Office of the State Treasurer", officialUrl: "https://www.treasurer.sc.gov/what-we-do/for-citizens/unclaimed-property-program/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("SC"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  SD: { state: "SD", name: "South Dakota", agency: "South Dakota State Treasurer", officialUrl: "https://southdakota.findyourunclaimedproperty.com/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("SD"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  TN: { state: "TN", name: "Tennessee", agency: "Tennessee Department of Treasury", officialUrl: "https://claimittn.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("TN"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  TX: { state: "TX", name: "Texas", agency: "Texas Comptroller of Public Accounts", officialUrl: "https://claimittexas.org/", accessMode: "gated_request", missingMoneyUrl: missingMoneyUrl("TX"), machineReadable: false, notes: "Statewide dataset is gated; request through the Comptroller data process. Local open data is not statewide." },
  UT: { state: "UT", name: "Utah", agency: "Utah State Treasurer", officialUrl: "https://mycash.utah.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("UT"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  VT: { state: "VT", name: "Vermont", agency: "Vermont State Treasurer", officialUrl: "https://www.vermonttreasurer.gov/content/unclaimed-property", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("VT"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  VA: { state: "VA", name: "Virginia", agency: "Virginia Department of the Treasury", officialUrl: "https://vamoneysearch.org/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("VA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  WA: { state: "WA", name: "Washington", agency: "Washington Department of Revenue", officialUrl: "https://ucp.dor.wa.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("WA"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  WV: { state: "WV", name: "West Virginia", agency: "West Virginia State Treasurer", officialUrl: "https://www.wvunclaimedproperty.gov/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("WV"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  WI: { state: "WI", name: "Wisconsin", agency: "Wisconsin Department of Revenue", officialUrl: "https://www.revenue.wi.gov/Pages/UnclaimedProperty/Home.aspx", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("WI"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
  WY: { state: "WY", name: "Wyoming", agency: "Wyoming State Treasurer", officialUrl: "https://statetreasurer.wyo.gov/unclaimed-property/", accessMode: "official_portal", missingMoneyUrl: missingMoneyUrl("WY"), machineReadable: false, notes: "Official portal; no public bulk feed confirmed." },
};

export const AVAILABLE_STATES = Object.keys(STATE_DIRECTORY);
export const OFFICIAL_STATE_URLS = Object.fromEntries(
  Object.entries(STATE_DIRECTORY).map(([state, entry]) => [state, entry.officialUrl]),
) as Record<string, string>;
