// @ts-ignore
import Database from "better-sqlite3";
import * as path from "path";
import * as fs from "fs";

const DB_PATH = process.env.DATABASE_URL || path.join(process.cwd(), "data.sqlite");
export const db = new Database(DB_PATH);

// Enable WAL mode for better concurrency
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

function columnExists(table: string, column: string): boolean {
  const info = db.prepare(`PRAGMA table_info(${table})`).all() as any[];
  return info.some((c) => c.name === column);
}

export function runMigrations() {
  const schemaPath = path.join(process.cwd(), "db", "schema.sql");
  if (!fs.existsSync(schemaPath)) {
    console.warn("No schema.sql found, skipping migrations");
    return;
  }

  const schema = fs.readFileSync(schemaPath, "utf-8");

  try {
    // Run the main schema first (CREATE TABLE IF NOT EXISTS etc.)
    db.exec(schema);

    // Safe column additions for future schema evolution
    if (!columnExists("leads", "last_enriched_at")) {
      db.exec("ALTER TABLE leads ADD COLUMN last_enriched_at DATETIME");
      console.log("[migrate] Added missing column: leads.last_enriched_at");
    }

    console.log("Migrations applied successfully");
  } catch (e: any) {
    console.error("Migration error:", e.message);
    throw e;
  }
}

export function seedRegulations() {
  const count = db.prepare("SELECT COUNT(*) as c FROM regulations").get() as { c: number };
  if (count.c > 0) return;

  const regulations = [
    { state: "AL", state_name: "Alabama", claim_form_url: "https://www.treasury.al.gov/Unclaimed-Property", required_documents: JSON.stringify(["Valid photo ID","Proof of address","Social Security card"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Ala. Code § 35-12-1 et seq." },
    { state: "AK", state_name: "Alaska", claim_form_url: "https://treasury.dor.alaska.gov/Unclaimed-Property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "AS 34.45.010 et seq." },
    { state: "AZ", state_name: "Arizona", claim_form_url: "https://azdor.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of authority (Power of Attorney)","Death certificate if deceased","Letters of office or will for estates","Affidavit Collection Personal Property under $75K"]), notarization_required: 0, heirship_affidavit_required: 1, probate_required_threshold: 75000, finder_fee_cap: 30, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "A.R.S. § 44-301 et seq.; § 44-322 (contract); § 44-327 (fee); license: Private Investigator ARS § 32-2410" },
    { state: "AR", state_name: "Arkansas", claim_form_url: "https://www.auditor.ar.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of address"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "A.C.A. § 18-28-201 et seq." },
    { state: "CA", state_name: "California", claim_form_url: "https://www.sco.ca.gov/upd_contact.html", required_documents: JSON.stringify(["Valid photo ID","Proof of Social Security Number","Documentation linking you to property"]), notarization_required: 1, heirship_affidavit_required: 1, probate_required_threshold: 166250, finder_fee_cap: 10, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "California Code of Civil Procedure § 1500 et seq.; § 1582" },
    { state: "CO", state_name: "Colorado", claim_form_url: "https://www.colorado.gov/treasury/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "C.R.S. § 38-13-101 et seq." },
    { state: "CT", state_name: "Connecticut", claim_form_url: "https://portal.ct.gov/OPM/Finance/Unclaimed-Property", required_documents: JSON.stringify(["Valid photo ID","Proof of address"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "CGS § 3-57a et seq." },
    { state: "DE", state_name: "Delaware", claim_form_url: "https://finance.delaware.gov/unclaimed-property/", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "12 Del. C. § 1198 et seq." },
    { state: "FL", state_name: "Florida", claim_form_url: "https://www.fltreasurehunt.gov", required_documents: JSON.stringify(["Valid photo ID","Proof of Social Security Number","Documentation linking you to property","Notarized claim form","Official Unclaimed Property Recovery Agreement per s. 717.135"]), notarization_required: 1, heirship_affidavit_required: 1, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 5, legal_reference: "Ch. 717, Florida Statutes; Rule 69I-20, F.A.C.; s. 717.135 (official form required)" },
    { state: "GA", state_name: "Georgia", claim_form_url: "https://dor.georgia.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "O.C.G.A. § 44-12-190 et seq." },
    { state: "HI", state_name: "Hawaii", claim_form_url: "https://hidot.hawaii.gov/programs/unclaimed-property/", required_documents: JSON.stringify(["Valid photo ID","Proof of address"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "HRS § 523A-1 et seq." },
    { state: "ID", state_name: "Idaho", claim_form_url: "https://www.sto.idaho.gov/unclaimed-property/", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Idaho Code § 14-501 et seq." },
    { state: "IL", state_name: "Illinois", claim_form_url: "https://icash.illinoistreasurer.gov/", required_documents: JSON.stringify(["Valid photo ID","Proof of Social Security Number","Documentation linking to property","$25K fidelity bond required","License: IL Finder License from State Treasurer"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: 10, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "765 ILCS 1026/1 et seq. (Revised Uniform Unclaimed Property Act); license $500 fee, 3yr term" },
    { state: "IN", state_name: "Indiana", claim_form_url: "https://indianaunclaimed.gov/", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "IC 32-34-1 et seq." },
    { state: "IA", state_name: "Iowa", claim_form_url: "https://www.iowatreasurer.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of address"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Iowa Code § 556.1 et seq." },
    { state: "KS", state_name: "Kansas", claim_form_url: "https://www.kansascash.com/", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "K.S.A. 58-3935 et seq." },
    { state: "KY", state_name: "Kentucky", claim_form_url: "https://treasury.ky.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "KRS 393A" },
    { state: "LA", state_name: "Louisiana", claim_form_url: "https://www.treasury.la.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "La. R.S. 9:151 et seq." },
    { state: "ME", state_name: "Maine", claim_form_url: "https://www.maine.gov/treasurer/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "33 M.R.S. § 1951 et seq." },
    { state: "MD", state_name: "Maryland", claim_form_url: "https://www.marylandtaxes.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Md. Code, Commercial Law § 17-101 et seq." },
    { state: "MA", state_name: "Massachusetts", claim_form_url: "https://www.mass.gov/orgs/unclaimed-property-division", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "M.G.L. c. 200A" },
    { state: "MI", state_name: "Michigan", claim_form_url: "https://www.michigan.gov/treasury/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "MCL 567.221 et seq." },
    { state: "MN", state_name: "Minnesota", claim_form_url: "https://www.mn.gov/commerce/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Minn. Stat. § 345.31 et seq." },
    { state: "MS", state_name: "Mississippi", claim_form_url: "https://www.treasury.ms.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Miss. Code Ann. § 89-12-1 et seq." },
    { state: "MO", state_name: "Missouri", claim_form_url: "https://www.treasurer.mo.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Mo. Rev. Stat. § 447.500 et seq." },
    { state: "MT", state_name: "Montana", claim_form_url: "https://mtreasurer.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Mont. Code Ann. § 70-9-801 et seq." },
    { state: "NE", state_name: "Nebraska", claim_form_url: "https://www.nebraska.gov/treasurer/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Neb. Rev. Stat. § 69-1301 et seq." },
    { state: "NV", state_name: "Nevada", claim_form_url: "https://nevadatreasurer.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: 10, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "NRS 120A" },
    { state: "NH", state_name: "New Hampshire", claim_form_url: "https://www.nh.gov/treasury/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "RSA 471-C" },
    { state: "NJ", state_name: "New Jersey", claim_form_url: "https://www.nj.gov/treasury/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "N.J.S.A. 46:30B-1 et seq." },
    { state: "NM", state_name: "New Mexico", claim_form_url: "https://www.nmsto.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "N.M.S.A. 1978 § 7-8A-1 et seq." },
    { state: "NY", state_name: "New York", claim_form_url: "https://www.osc.state.ny.us/unclaimed-funds", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Abandoned Property Law" },
    { state: "NC", state_name: "North Carolina", claim_form_url: "https://www.nctreasurer.com/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "N.C.G.S. § 116B-1 et seq." },
    { state: "ND", state_name: "North Dakota", claim_form_url: "https://www.land.nd.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "N.D.C.C. § 47-30.1-01 et seq." },
    { state: "OH", state_name: "Ohio", claim_form_url: "https://www.ohio.gov/treasurer/unclaimed-funds", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Ohio Rev. Code § 169.01 et seq." },
    { state: "OK", state_name: "Oklahoma", claim_form_url: "https://www.ok.gov/treasurer/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Okla. Stat. tit. 60, § 651 et seq." },
    { state: "OR", state_name: "Oregon", claim_form_url: "https://www.oregon.gov/treasury/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "ORS 98.302 et seq." },
    { state: "PA", state_name: "Pennsylvania", claim_form_url: "https://www.patreasury.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "72 P.S. § 1301.1 et seq." },
    { state: "RI", state_name: "Rhode Island", claim_form_url: "https://www.treasury.ri.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "R.I. Gen. Laws § 33-21.2-1 et seq." },
    { state: "SC", state_name: "South Carolina", claim_form_url: "https://treasurer.sc.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "S.C. Code Ann. § 27-18-10 et seq." },
    { state: "SD", state_name: "South Dakota", claim_form_url: "https://sdtreasurer.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "S.D. Codified Laws § 43-41B-1 et seq." },
    { state: "TN", state_name: "Tennessee", claim_form_url: "https://treasury.tn.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: 10, finder_contract_required: 1, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Tenn. Code Ann. § 66-29-101 et seq." },
    { state: "TX", state_name: "Texas", claim_form_url: "https://www.claimittexas.org", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: 10, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Tex. Prop. Code § 72.001 et seq." },
    { state: "UT", state_name: "Utah", claim_form_url: "https://www.ucp.utah.gov", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Utah Code Ann. § 67-4a-101 et seq." },
    { state: "VT", state_name: "Vermont", claim_form_url: "https://www.vermonttreasurer.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "32 V.S.A. § 1241 et seq." },
    { state: "VA", state_name: "Virginia", claim_form_url: "https://www.vamoneysearch.org", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Va. Code Ann. § 55.1-2500 et seq." },
    { state: "WA", state_name: "Washington", claim_form_url: "https://www.washingtonwager.com", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "RCW 63.29" },
    { state: "WV", state_name: "West Virginia", claim_form_url: "https://www.wvtreasury.com/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "W. Va. Code § 36-8-1 et seq." },
    { state: "WI", state_name: "Wisconsin", claim_form_url: "https://www.revenue.wi.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Wis. Stat. § 177" },
    { state: "WY", state_name: "Wyoming", claim_form_url: "https://treasurer.wyo.gov/unclaimed-property", required_documents: JSON.stringify(["Valid photo ID","Proof of ownership"]), notarization_required: 0, heirship_affidavit_required: 0, probate_required_threshold: 0, finder_fee_cap: null, finder_contract_required: 0, contract_must_be_notarized: 0, cooling_off_days: 0, legal_reference: "Wyo. Stat. Ann. § 34-24-101 et seq." },
  ];

  const stmt = db.prepare(`
    INSERT INTO regulations (state, state_name, claim_form_url, required_documents, notarization_required, heirship_affidavit_required, probate_required_threshold, finder_fee_cap, finder_contract_required, contract_must_be_notarized, cooling_off_days, legal_reference)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  for (const reg of regulations) {
    stmt.run(reg.state, reg.state_name, reg.claim_form_url, reg.required_documents, reg.notarization_required, reg.heirship_affidavit_required, reg.probate_required_threshold, reg.finder_fee_cap, reg.finder_contract_required, reg.contract_must_be_notarized, reg.cooling_off_days, reg.legal_reference);
  }
  console.log(`Seeded ${regulations.length} state regulations`);
}
